### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by sebastienvg** [joejacobs/whois-server#1]
I have the node.js up and running, now how do I do to lookup a domain?

**Comment by joejacobs** [comment]
Try whois -h localhost:9000 domain.name

**Comment by sebastienvg** [comment]
That's how I had to do

whois --host=whois-server.tld --port=9000 domain-to.lookup

for some reason localhost won't work, but if I use the the actual hostname of the whois server it works. 

Thanks a lot for the piece of code.
